### ISSUE TITLE
Does not work on ubuntu: 'No module named app.console'

### ISSUE THREAD

**Issue by teward** [zacscott/dos-over-tor#2]
This tool does not function properly and when executing it, you get this, even if you are in the proper directory tree location to run main.py.

````
$ python ./main.py --help
Traceback (most recent call last):
  File "./main.py", line 3, in <module>
    import app.console
ImportError: No module named app.console
````

**Comment by zacscott** [comment]
@teward, Im guessing that is a Python2 issue, it only supports Python 3 :D

**Comment by zacscott** [comment]
@teward I've updated the readme to reflect that this is only Python3 compatible, realised it wasn't mentioned anywhere 😊  

Should be easy enough to make Python2 compat, I just don't have time at the moment

**Comment by teward** [comment]
I'd offer to make it Py2 compat if you wish.

However if you intend Py3 compat I would suggest a couple version checks.  I'll make a PR for such a check.

**Comment by zacscott** [comment]
Happy for you to make it Py 2 compat if you want :)
